### ISSUE TITLE
Support ghc-8.0.1

### ISSUE THREAD

**Issue by int-e** [lambdabot/lambdabot#145]
As usual this will take some time. Using

    cabal install --allow-newer=$(ghc-pkg list --global --names-only --simple-output | sed 's/ /,/g'),HTTP lambdabot*/

there are four packages that need work:

- [x]    flexible-defaults (0.0.1.1)   -- template haskell changes, https://github.com/mokus0/flexible-defaults/issues/3
- [x]    hint (0.5.2)                  -- ghc internal logger changes, https://github.com/mvdan/hint/issues/1
- [x]    mueval (0.9.1.1.2)            -- hint changes, https://github.com/gwern/mueval/issues/14
- [x]    safecopy (0.9.0.1)            -- template haskell changes, https://github.com/acid-state/safecopy/issues/37

**Comment by int-e** [comment]
safecopy has an unreleased fix, cf. https://github.com/acid-state/safecopy/issues/37

**Comment by int-e** [comment]
for hint, see https://github.com/mvdan/hint/issues/1

**Comment by int-e** [comment]
for mueval, see https://github.com/gwern/mueval/issues/14

**Comment by int-e** [comment]
for flexible-defaults, see https://github.com/mokus0/flexible-defaults/issues/3

**Comment by int-e** [comment]
I tried this again, this time without relaxing upper bounds. Four packages remain:

- [ ] hint -- needs a new release, https://github.com/mvdan/hint/issues/1
- [ ] mueval -- hint changes, https://github.com/gwern/mueval/issues/14
- [ ] unlambda -- base upper bound, https://github.com/abbradar/unlambda/issues/2
- [ ] brainfuck -- base upper bound, https://github.com/abbradar/brainfuck/issues/1
