### ISSUE TITLE
support ghc 8.4

### ISSUE THREAD

**Issue by int-e** [lambdabot/lambdabot#168]
As usual some dependencies are broken by the new ghc.

#### new Semigroup superclass of Monoid
  * [x] data-inttrie, see https://github.com/luqui/data-inttrie/issues/6
  * [x] flexible-defaults, see https://github.com/mokus0/flexible-defaults/issues/5 and https://github.com/mokus0/flexible-defaults/pull/6
  * [x] arrows

#### misc
  * [x] hint needs a release, cf. https://github.com/mvdan/hint/issues/60
  * [x] probably not mueval

#### lambdabot changes
  * [x] lambdabot-core/src/Lambdabot/Config.hs: uses Typeable1 (which is now subsumed by Typeable)
  * [x] lambdabot-haskell-plugins/src/Lambdabot/Plugin/Haskell/Free/Type.hs: clashing (<>) (ditto: Expr,hs, Theorem.hs)
  * [x] release on hackage

**Comment by int-e** [comment]
See also https://github.com/lambdabot/lambdabot/tree/ghc-8.4.1 (note that this is *not* meant to be merged).

**Comment by int-e** [comment]
@peti has taken over flexible-defaults, see https://github.com/peti/flexible-defaults

**Comment by int-e** [comment]
@peti, do you see any reason for not releasing this on hackage as lambdabot-5.1.0.2?

**Comment by peti** [comment]
No, the new version works fine for me. I'd be hugely in favor of a new release so that I can get `lambdabot-core` etc. re-added to Hackage, too

**Comment by int-e** [comment]
I've released lambdabot 5.1.0.2.

**Comment by int-e** [comment]
Actually that went slightly wrong... but should be fine now.

See also https://github.com/haskell/hackage-server/issues/768

(I'm not sure whether I wrote that down anywhere, but I'm trying to adapt the following versioning policy: There's a global version of lambdabot (5.1.0.3 now), but only subpackages that have actually changed get there version bumped and uploaded when a new release is made. So when I uploaded lambdabot-haskell-plugins 5.1.0.2, I should have made a 5.1.0.2 tag.)
